XMPP_DOMAIN = "localhost"

ORDER_AGENT_JID = "order@localhost"
ORDER_AGENT_PASSWORD = "order123"

INVENTORY_AGENT_JID = "inventory@localhost"
INVENTORY_AGENT_PASSWORD = "inventory123"

CHEF_AGENT_JID = "chef@localhost"
CHEF_AGENT_PASSWORD = "chef123"

DELIVERY_AGENT_JID = "delivery@localhost"
DELIVERY_AGENT_PASSWORD = "delivery123"

INVENTORY_FAILURE_RATE = 0.20
CHEF_FAILURE_RATE = 0.10
DELIVERY_FAILURE_RATE = 0.15