from enum import Enum


class Performative(str, Enum):

    NEW_ORDER = "NEW_ORDER"

    CHECK_INVENTORY = "CHECK_INVENTORY"

    INVENTORY_OK = "INVENTORY_OK"

    INVENTORY_FAILED = "INVENTORY_FAILED"

    START_COOKING = "START_COOKING"

    FOOD_READY = "FOOD_READY"

    ASSIGN_DELIVERY = "ASSIGN_DELIVERY"

    DELIVERY_ASSIGNED = "DELIVERY_ASSIGNED"

    ORDER_COMPLETED = "ORDER_COMPLETED"

    ERROR = "ERROR"