from enum import Enum


class Performative(str, Enum):
    NEW_ORDER = "NEW_ORDER"

    CHECK_INVENTORY = "CHECK_INVENTORY"

    INVENTORY_OK = "INVENTORY_OK"

    INVENTORY_FAILED = "INVENTORY_FAILED"

    PREPARE_ORDER = "PREPARE_ORDER"

    ORDER_READY = "ORDER_READY"

    ASSIGN_DRIVER = "ASSIGN_DRIVER"

    DELIVERY_ASSIGNED = "DELIVERY_ASSIGNED"

    COMPLETE_ORDER = "COMPLETE_ORDER"

    ERROR = "ERROR"