from enum import Enum


class OrderStatus(Enum):

    RECEIVED = "RECEIVED"

    CHECKING_INVENTORY = "CHECKING_INVENTORY"

    INVENTORY_CONFIRMED = "INVENTORY_CONFIRMED"

    COOKING = "COOKING"

    READY = "READY"

    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"

    DELIVERED = "DELIVERED"